steps:
  - name: Probo site setup
    plugin: Drupal
    makeFile: build-bear.make
    installArgs: "--site-name='Install Profile Drupal Plugin Demo'"
    clearCaches: true
    profileName: bear
    runInstall: true
    revertFeatures: true
